package docsgen

import (
	"bytes"
	"context"
	"fmt"
	"html/template"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"datascape.dev/platformctl/internal/artifact"
	"datascape.dev/platformctl/internal/resource"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

func FoundationDocs() []artifact.File {
	return []artifact.File{
		{Path: "docs/index.md", Mode: 0o644, Content: []byte("# Datascape Platform Compiler\n\nThis bundle was generated by the deterministic compiler. Bundles include resource definitions, provider selections, binding resolutions, graph state, policy decisions, provider-owned target artifacts, verification, recovery, provenance, and checksums.\n"), Deterministic: true},
		{Path: "docs/specification/reference.md", Mode: 0o644, Content: []byte("# Specification Reference\n\nPrimary authoring uses typed components, connections, and bindings. Connections reference `SecretReference` resources; typed bindings such as `CDCBinding`, `StreamPublishBinding`, and `StreamArchiveBinding` normalize to capability graph edges. Extension resources are admitted by `ResourceDefinition`, `Provider`, `ProviderInstance`, `BindingDefinition`, and generic `Binding` declarations.\n"), Deterministic: true},
	}
}

type page struct {
	Title string
	Path  string
	Body  template.HTML
}

type siteModel struct {
	Title   string
	Current string
	Pages   []page
	Body    template.HTML
}

// BuildSite converts the maintained Markdown documentation and generated API
// reference into a navigable, dependency-free static HTML site.
func BuildSite(ctx context.Context, source string) ([]artifact.File, error) {
	if source == "" {
		source = "docs"
	}
	markdown := goldmark.New(goldmark.WithExtensions(extension.GFM, extension.Footnote, extension.Typographer))
	pages := make([]page, 0)
	assets := make([]artifact.File, 0)
	err := filepath.WalkDir(source, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if ctx.Err() != nil {
			return ctx.Err()
		}
		if entry.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if strings.EqualFold(filepath.Ext(rel), ".md") {
			pages = append(pages, renderMarkdownPage(markdown, rel, content))
			return nil
		}
		assets = append(assets, artifact.File{Path: rel, Mode: 0o644, Content: content, Deterministic: true})
		return nil
	})
	if err != nil {
		return nil, err
	}
	pages = append(pages, renderMarkdownPage(markdown, "reference/api.md", []byte(apiReference())))
	sort.SliceStable(pages, func(i, j int) bool { return pages[i].Path < pages[j].Path })
	files := make([]artifact.File, 0, len(pages)+len(assets)+4)
	for _, item := range pages {
		content, err := renderHTML(siteModel{Title: item.Title, Current: item.Path, Pages: pages, Body: item.Body})
		if err != nil {
			return nil, err
		}
		files = append(files, artifact.File{Path: item.Path, Mode: 0o644, Content: content, Deterministic: true})
	}
	files = append(files, assets...)
	files = append(files,
		artifact.File{Path: "assets/site.css", Mode: 0o644, Content: []byte(siteCSS), Deterministic: true},
		artifact.File{Path: "assets/site.js", Mode: 0o644, Content: []byte(siteJS), Deterministic: true},
		artifact.File{Path: "site-manifest.txt", Mode: 0o644, Content: []byte(siteManifest(pages)), Deterministic: true},
	)
	files = artifact.Normalize(files)
	if err := validateLinks(files); err != nil {
		return nil, err
	}
	return files, nil
}

var hrefRE = regexp.MustCompile(`href="([^"]+)"`)

func validateLinks(files []artifact.File) error {
	known := map[string]bool{}
	for _, file := range files {
		known[file.Path] = true
	}
	for _, file := range files {
		if filepath.Ext(file.Path) != ".html" {
			continue
		}
		for _, match := range hrefRE.FindAllStringSubmatch(string(file.Content), -1) {
			href := match[1]
			if href == "" || strings.HasPrefix(href, "#") || strings.Contains(href, "://") || strings.HasPrefix(href, "mailto:") {
				continue
			}
			if index := strings.IndexAny(href, "#?"); index >= 0 {
				href = href[:index]
			}
			target := path.Clean(path.Join(path.Dir(file.Path), href))
			if !known[target] {
				return fmt.Errorf("broken documentation link in %s: %s resolves to %s", file.Path, match[1], target)
			}
		}
	}
	return nil
}

func renderMarkdownPage(markdown goldmark.Markdown, rel string, content []byte) page {
	var rendered bytes.Buffer
	_ = markdown.Convert(content, &rendered)
	body := strings.ReplaceAll(rendered.String(), `.md"`, `.html"`)
	body = strings.ReplaceAll(body, `.md#`, `.html#`)
	output := strings.TrimSuffix(rel, filepath.Ext(rel)) + ".html"
	if output == "index.html" {
		output = "index.html"
	}
	return page{Title: markdownTitle(content, rel), Path: output, Body: template.HTML(body)}
}

func markdownTitle(content []byte, fallback string) string {
	for _, line := range strings.Split(string(content), "\n") {
		if strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "# "))
		}
	}
	return strings.TrimSuffix(filepath.Base(fallback), filepath.Ext(fallback))
}

func apiReference() string {
	var b strings.Builder
	b.WriteString("# Generated API Reference\n\nThis page is generated from the same built-in definitions used by validation.\n\n")
	for _, def := range resource.BuiltinDefinitions() {
		fmt.Fprintf(&b, "## %s\n\n- **apiVersion:** `%s`\n- **scope:** `%s`\n- **category:** `%s`\n", def.Kind, def.APIVersion, def.Scope, def.Category)
		if def.ProviderType != "" {
			fmt.Fprintf(&b, "- **provider type:** `%s`\n", def.ProviderType)
		}
		if len(def.Capabilities) > 0 {
			fmt.Fprintf(&b, "- **capabilities:** `%s`\n", strings.Join(def.Capabilities, "`, `"))
		}
		if len(def.Schema) > 0 {
			if required, ok := def.Schema["required"].([]string); ok && len(required) > 0 {
				fmt.Fprintf(&b, "- **required:** `%s`\n", strings.Join(required, "`, `"))
			}
			if properties, ok := def.Schema["properties"].(map[string]any); ok {
				keys := make([]string, 0, len(properties))
				for key := range properties {
					keys = append(keys, key)
				}
				sort.Strings(keys)
				b.WriteString("\n| Field | Type |\n|---|---|\n")
				for _, key := range keys {
					prop, _ := properties[key].(map[string]any)
					fmt.Fprintf(&b, "| `spec.%s` | `%v` |\n", key, prop["type"])
				}
			}
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderHTML(model siteModel) ([]byte, error) {
	var out bytes.Buffer
	if err := siteTemplate.Execute(&out, model); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

func siteManifest(pages []page) string {
	var b strings.Builder
	for _, item := range pages {
		b.WriteString(item.Path)
		b.WriteByte('\n')
	}
	return b.String()
}

func relativePrefix(path string) string {
	depth := strings.Count(path, "/")
	return strings.Repeat("../", depth)
}

var siteTemplate = template.Must(template.New("site").Funcs(template.FuncMap{"prefix": relativePrefix}).Parse(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{.Title}} · Datascape</title><link rel="stylesheet" href="{{prefix .Current}}assets/site.css"></head>
<body><aside><a class="brand" href="{{prefix .Current}}index.html">Datascape</a><input id="doc-search" aria-label="Filter documentation" placeholder="Filter documentation">
<nav id="doc-nav">{{range .Pages}}<a data-doc-link href="{{prefix $.Current}}{{.Path}}" class="{{if eq .Path $.Current}}active{{end}}">{{.Title}}</a>{{end}}</nav></aside>
<main><article>{{.Body}}</article><footer>Generated by <code>platformctl docs build</code>.</footer></main>
<script src="{{prefix .Current}}assets/site.js"></script></body></html>`))

const siteCSS = `:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#172033;background:#f7f9fc}*{box-sizing:border-box}body{margin:0;display:grid;grid-template-columns:310px minmax(0,1fr);min-height:100vh}aside{position:sticky;top:0;height:100vh;overflow:auto;background:#111827;color:#e5e7eb;padding:1.2rem}.brand{display:block;color:#fff;font-size:1.35rem;font-weight:750;text-decoration:none;margin-bottom:1rem}input{width:100%;padding:.65rem;border:1px solid #4b5563;border-radius:.45rem;background:#1f2937;color:#fff;margin-bottom:.8rem}nav a{display:block;color:#cbd5e1;text-decoration:none;padding:.42rem .55rem;border-radius:.35rem;font-size:.9rem}nav a:hover,nav a.active{background:#24324a;color:#fff}main{min-width:0;padding:2.5rem clamp(1.2rem,5vw,5rem)}article{max-width:1000px;background:#fff;border:1px solid #e2e8f0;border-radius:.75rem;padding:clamp(1.2rem,4vw,3rem);box-shadow:0 10px 30px #0f172a0a}h1,h2,h3{color:#0f172a;line-height:1.2}h2{margin-top:2.4rem;border-bottom:1px solid #e2e8f0;padding-bottom:.45rem}p,li{line-height:1.65}code{background:#eef2f7;padding:.12rem .3rem;border-radius:.25rem}pre{overflow:auto;background:#0f172a;color:#e2e8f0;padding:1rem;border-radius:.55rem}pre code{background:transparent;padding:0}table{width:100%;border-collapse:collapse}th,td{text-align:left;border:1px solid #dbe2ea;padding:.55rem}th{background:#f1f5f9}footer{max-width:1000px;padding:1.5rem 0;color:#64748b}@media(max-width:850px){body{display:block}aside{position:relative;height:auto}main{padding:1rem}}`

const siteJS = `const q=document.querySelector('#doc-search');if(q){q.addEventListener('input',()=>{const v=q.value.toLowerCase();document.querySelectorAll('[data-doc-link]').forEach(a=>a.hidden=!a.textContent.toLowerCase().includes(v));});}`
